# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GoCoRo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GoCoRo
  pod 'SVProgressHUD'
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.8'
  pod 'SDWebImage/WebP'
  pod 'Realm'
  # pod 'Charts'
  pod 'AWERatingBar', '~> 0.1.0'
end
